### PR TITLE
Fix layout for development documentation pages

### PR DESCRIPTION
**Pull request by KyCodeHuynh**
Behold before: 

screen shot 2016-02-09 at 6 14 52 pm

And after: 

screen shot 2016-02-09 at 6 14 59 pm

### CODE REVIEW

**Comment by KyCodeHuynh** [comment]
I also set up a nicer landing page for the docs and figured out how to exclude it from the navbar.

**Comment by nbedi** [comment]
Should this all be moved to the repos wiki instead? No real preference, just a thought.

**Comment by KyCodeHuynh** [comment]
Either one would work, though moving it to the wiki would be nice for centralizing all the documentation here and closer to the development side of things.

**Comment by KyCodeHuynh** [comment]
@liddiard Wanna have a look at this and confirm that the header doesn't appear in the navbar?

**Comment by simzou** [comment]
Looks good to me! Thanks @KyCodeHuynh! Sorry for the delay on this. And yea we should probably have this in the wiki as well.

**Pull request merged**
